modLoader="javafml"
loaderVersion="${loaderVersionRange}"
license="MIT"
#issueTrackerURL=""

[[mods]]
modId="ethylene"
version="${modVersion}"
displayName="Ethylene"
#updateJSONURL=""
#displayURL=""
#logoFile="logo.png"
#credits=""
authors="TonimatasDEV"
# TODO: Do a description.
description='''
I need to put a description
'''

[[mixins]]
config="ethylene.mixins.json"

[[accessTransformers]]
file="accesstransformer.cfg"

[[dependencies.ethylene]]
modId="neoforge"
type="required"
versionRange="${neoVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.ethylene]]
modId="minecraft"
type="required"
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"
